<?php

include_once __DIR__ . '/../../model/AppointmentModel.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-02-17 at 03:07:19.
 */
class AppointmentModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AppointmentModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        include_once __DIR__ . '/../../libs/configuration.php';
        $this->object = AppointmentModel::singleton();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppointmentModel::register_appointment
     * @todo   Implement testRegister_appointment().
     */
    public function testRegister_appointment() { // 1 ------------------------------------- 

        /* $response = $this->object->register_appointment( 302900456, "2021-12-06", 
          "10:00am", "300000888", 'UnitTest', "pendiente",
          "UnitTest", "UnitTest");

          // Se espera respuesta vacía
          $this->assertEmpty($response); */
    }

    /**
     * @covers AppointmentModel::register_functionary
     * @todo   Implement testRegister_functionary().
     */
    public function testRegister_functionary() { // 2 ------------------------------------- 

        /* $response = $this->object->register_functionary(
          302900456, 'Username', "Lastname", "Second Lastname",
          "85858585", "89898989", "1999-12-06", 'M', "Tecnico",
          "Cartago", "Turrialba", "La Suiza", "Viudo(a)", "absd", "87878787",
          "example@gmail.com", "321", "2022-12-06", "nada", "robos",
          "central", "2019-12-06");

          // Se espera respuesta vacía
          $this->assertEmpty($response); */
    }

    /**
     * @covers AppointmentModel::get_appointments_by_filter
     * @todo   Implement testGet_appointments_by_filter().
     */
    public function testGet_appointments_by_filter() { // 3 ------------------------------------- 
        $response1 = $this->object->get_appointments_by_filter(302900101, 1023, "2021-02-22", "2021-02-24", 308880182, "M");

        // Se espera vacío
        $this->assertEmpty($response1);

        $response2 = $this->object->get_appointments_by_filter('', '', '', '', '', '');

        // Se espera una lista de resultados 
        $this->assertGreaterThanOrEqual(1, count($response2));
    }

    /**
     * @covers AppointmentModel::get_appointment_by_id_and_identification
     * @todo   Implement testGet_appointment_by_id_and_identification().
     */
    public function testGet_appointment_by_id_and_identification() { // 4 ------------------------------------- 
        // Remove the following lines when you implement this test.
        $response1 = $this->object->
                get_appointment_by_id_and_identification(1, 108490156);

        // Se espera vacío
        $this->assertEmpty($response1);

        $response2 = $this->object->
                get_appointment_by_id_and_identification(9, 108490156);

        // Se espera un resultado 
        $this->assertEquals(9, $response2[0]['pk_id_cita']);
        $this->assertEquals(108490156, $response2[0]['pk_cedula_usuario']);
    }

    /**
     * @covers AppointmentModel::get_appointment_detail
     * @todo   Implement testGet_appointment_detail().
     */
    public function testGet_appointment_detail() { // 5 ------------------------------------- 
        $response1 = $this->object->get_appointment_detail(4);

        // Se espera vacío
        $this->assertEmpty($response1);

        $response2 = $this->object->get_appointment_detail(5);

        // Se espera un resultado 
        $this->assertEquals(5, $response2[0]['pk_id_cita']);
    }

}
