<?php

include_once './../model/AppointmentModel.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-02-17 at 03:07:19.
 */
class AppointmentModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AppointmentModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        include_once './../libs/configuration.php';
        $this->object = AppointmentModel::singleton();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppointmentModel::register_appointment
     * @todo   Implement testRegister_appointment().
     */
    public function testRegister_appointment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppointmentModel::register_functionary
     * @todo   Implement testRegister_functionary().
     */
    public function testRegister_functionary() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppointmentModel::get_appointments_by_filter
     * @todo   Implement testGet_appointments_by_filter().
     */
    public function testGet_appointments_by_filter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppointmentModel::get_appointments_quantity
     * @todo   Implement testGet_appointments_quantity().
     */
    public function testGet_appointments_quantity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppointmentModel::modify_appointment
     * @todo   Implement testModify_appointment().
     */
    public function testModify_appointment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppointmentModel::get_appointment_by_id_and_identification
     * @todo   Implement testGet_appointment_by_id_and_identification().
     */
    public function testGet_appointment_by_id_and_identification() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppointmentModel::get_appointment_detail
     * @todo   Implement testGet_appointment_detail().
     */
    public function testGet_appointment_detail() {
        
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppointmentModel::cancelAppointmentById
     * @todo   Implement testCancelAppointmentById().
     */
    public function testCancelAppointmentById() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
