<?php

include_once './../model/UserModel.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-02-17 at 03:09:58.
 */
class UserModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UserModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        include_once './../libs/configuration.php';
        $this->object = UserModel::singleton();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers UserModel::register_professional
     * @todo   Implement testRegister_professional().
     */
    public function testRegister_professional() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserModel::searchProfessional
     * @todo   Implement testSearchProfessional().
     */
    public function testSearchProfessional() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserModel::delete_professional
     * @todo   Implement testDelete_professional().
     */
    public function testDelete_professional() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserModel::update_professional
     * @todo   Implement testUpdate_professional().
     */
    public function testUpdate_professional() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserModel::obtain_information_to_modify
     * @todo   Implement testObtain_information_to_modify().
     */
    public function testObtain_information_to_modify() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
